name: CI/CD
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  SonarCloud-And-Tests:
    name: SonarCloud-And-Tests
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      MONGO: ${{ secrets.MONGO }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: ${{ secrets.PORT }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  
    - name: Setup Node.js
      uses: actions/setup-node@v3
    - name: Dependencies
      run: npm ci
    - name: Unit Tests
      run: npm test --coverage
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
    - name: Log in to docker hub 
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
    - name: build and  Push Docker image
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/dracosnape-app:latest
    - name: Report Status
      if: always()
      uses: act10ns/slack@v2.1.0
      with:
        status: ${{ job.status }}

