name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Tests-IS:
    name: Tests-IS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      MONGO: ${{ secrets.MONGO }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: ${{ secrets.PORT }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Unit Tests
      run: npm test --coverage

    - name: Log in to docker hub 
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}

    - name: build and  Push Docker image
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/dracosnape-app:latest

    - name: Report Status
      if: always()
      uses: act10ns/slack@v2.1.0
      with:
        status: ${{ job.status }}

  SonarCloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: Tests-IS
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name : Git checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master

