name: CI-CD

on:
  pull_request:
    branches: [ "staging", "main" ]
    types: [opened, synchronize, reopened]

jobs:
  TESTS-SONARQUBE:
    name: TESTS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      MONGO: ${{ secrets.MONGO }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: ${{ secrets.PORT }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Dependencies
      id: Dependencies
      run: npm ci
    - name: Build
      id: Build
      run: npm run build
    - name: Unit Tests
      id: UnitTests
      run: npm test

    - name: Report Status
      if: always()
      uses: act10ns/slack@v2.1.0
      with:
        status: ${{ job.status }}

