name: Slack Merge Notification

on:
  pull_request:
    branches: [ "main" ]
    types: [closed]

jobs:
  slack:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
         args: |
           {
             "channel": "C071K0XLEDR",
             "blocks": [
               {
                 "type": "section",
                 "text": {
                   "type": "mrkdwn",
                   "text": "*Pull Request Merged:* ${{ github.event.pull_request.title }}"
                 }
               },
               {
                 "type": "section",
                 "text": {
                   "type": "mrkdwn",
                   "text": "*Who?:* ${{ github.event.pull_request.user.login }}\n*Merged by:* ${{ github.event.pull_request.merged_by.login }}"
                 }
               },
               {
                 "type": "section",
                 "text": {
                   "type": "mrkdwn",
                   "text": "<${{ github.event.pull_request.html_url }}|View Pull Request>"
                 }
               }
             ]
           }
