name: Build
on:
 push:
   branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    env:
      MONGO: ${{ secrets.MONGO }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: ${{ secrets.PORT }}

    steps:
      - name : Git checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Install dependencies 
        run: npm ci
  
      - name: Build project
        run: npm run build --if-present


      - name: Test and coverage
        run: npm test --coverage


      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          MONGO: ${{ secrets.MONGO }}